## Importing Libraries

In [1]:
import numpy as np
import  pandas as pd

## Loading Data

In [2]:
df = pd.read_csv('zomato.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

## Data Inspection

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 6.7 MB

In [4]:
df.describe()

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [5]:
df.describe(include='all')

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
count,51717,51717,51717,51717,51717,43942,51717.000000,50509,51696,51490,23639,51672,51371,51717,51717,51717,51717
unique,51717,11495,8792,2,2,64,NaN,14926,93,93,5271,2723,70,22513,9098,7,30
top,https://www.zomato.com/bangalore/jalsa-banasha...,Delivery Only,Cafe Coffee Day,Yes,No,NEW,NaN,080 43334321,BTM,Quick Bites,Biryani,North Indian,300,[],[],Delivery,BTM
freq,1,128,96,30444,45268,2208,NaN,216,5124,19132,182,2913,7576,7595,39617,25942,3279
mean,NaN,NaN,NaN,NaN,NaN,NaN,283.697527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,803.838853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,198.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,16832.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.duplicated().sum()

np.int64(0)

In [14]:
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_values

dish_liked                     28078
rate                            7775
phone                           1208
approx_cost(for two people)      346
rest_type                        227
cuisines                          45
location                          21
url                                0
address                            0
votes                              0
name                               0
online_order                       0
book_table                         0
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [15]:
missing_values_percentage = (missing_values / len(df)) * 100
missing_values_percentage

dish_liked                     54.291626
rate                           15.033741
phone                           2.335789
approx_cost(for two people)     0.669026
rest_type                       0.438927
cuisines                        0.087012
location                        0.040606
url                             0.000000
address                         0.000000
votes                           0.000000
name                            0.000000
online_order                    0.000000
book_table                      0.000000
reviews_list                    0.000000
menu_item                       0.000000
listed_in(type)                 0.000000
listed_in(city)                 0.000000
dtype: float64

In [21]:
print("\nDish Liked Values:")
print(df["dish_liked"].value_counts(dropna=False).head(15))

Dish Liked Values:
dish_liked
NaN                 28078
Biryani               182
Chicken Biryani        73
Friendly Staff         69
Waffles                68
Paratha                57
Masala Dosa            56
Rooftop Ambience       42
Coffee                 42
Pizza                  38
Burgers                33
Cocktails              29
Prompt Service         27
Mutton Biryani         27
Noodles                26
Name: count, dtype: int64

In [17]:
print("\nRating Values:")
print(df["rate"].value_counts(dropna=False).head(15))

Rating Values:
rate
NaN       7775
NEW       2208
3.9/5     2098
3.8/5     2022
3.7/5     2011
3.9 /5    1874
3.8 /5    1851
3.7 /5    1810
3.6/5     1773
4.0/5     1609
4.0 /5    1574
3.6 /5    1543
4.1/5     1474
4.1 /5    1474
3.5/5     1431
Name: count, dtype: int64

In [22]:
print("\nPhone Values:")
print(df["phone"].value_counts(dropna=False).head(15))

print("\nLocation Values:")

Phone Values:
phone
NaN               1208
080 43334321       216
080 43334333       167
+91 7005889963      78
+91 8197170008      75
+91 7710055553      58
080 33994444        57
+91 8970010111      57
+91 7700020020      54
+91 8880141000      46
+91 9831810436      42
18001208242         40
+91 9036011861      39
080 43758178        38
+91 9036070410      37
Name: count, dtype: int64

Location Values:

In [23]:
print("\nApprox Cost Values:")
print(df["approx_cost(for two people)"].value_counts(dropna=False).head(15))

Approx Cost Values:
approx_cost(for two people)
300      7576
400      6562
500      4980
200      4857
600      3714
250      2959
800      2285
150      2066
700      1948
350      1763
1,000    1637
450      1417
100       993
1,200     993
1,500     971
Name: count, dtype: int64

In [24]:
print("\nRest Type Values:")
print(df["rest_type"].value_counts(dropna=False).head(15))

Rest Type Values:
rest_type
Quick Bites           19132
Casual Dining         10330
Cafe                   3732
Delivery               2604
Dessert Parlor         2263
Takeaway, Delivery     2037
Casual Dining, Bar     1154
Bakery                 1141
Beverage Shop           867
Bar                     697
Food Court              624
Sweet Shop              468
Bar, Casual Dining      425
Lounge                  396
Pub                     357
Name: count, dtype: int64

In [25]:
print("\nCuisines Values:")
print(df["cuisines"].value_counts(dropna=False).head(15))

Cuisines Values:
cuisines
North Indian                           2913
North Indian, Chinese                  2385
South Indian                           1828
Biryani                                 918
Bakery, Desserts                        911
Fast Food                               803
Desserts                                766
Cafe                                    756
South Indian, North Indian, Chinese     726
Bakery                                  651
Chinese                                 556
Ice Cream, Desserts                     417
Chinese, North Indian                   415
Mithai, Street Food                     372
Desserts, Ice Cream                     354
Name: count, dtype: int64

In [26]:
print("\nLocation Values:")
print(df["location"].value_counts(dropna=False).head(15))

Location Values:
location
BTM                      5124
HSR                      2523
Koramangala 5th Block    2504
JP Nagar                 2235
Whitefield               2144
Indiranagar              2083
Jayanagar                1926
Marathahalli             1846
Bannerghatta Road        1630
Bellandur                1286
Electronic City          1258
Koramangala 1st Block    1238
Brigade Road             1218
Koramangala 7th Block    1181
Koramangala 6th Block    1156
Name: count, dtype: int64

In [28]:
print("\nAddress Values:")
print(df["address"].value_counts(dropna=False).head(15))

Address Values:
address
Delivery Only                                                            128
14th Main, 4th Sector, HSR, Bangalore                                     71
The Ritz-Carlton, 99, Residency Road, Bangalore                           61
Citrus Hotels, 34, Cunningham Road, Bangalore                             53
Conrad Bengaluru, Kensington Road, Ulsoor, Bangalore                      49
710, Thubarahalli, Varthur Main Road, Whitefield, Bangalore               46
1, 100 Feet Ring Road, 1st Phase, 2nd Stage, BTM, Bangalore               43
40/2, Lavelle Road, Bangalore                                             41
The Park Bangalore, 14/7, MG Road, Bangalore                              38
Radisson Blu, 1, Palace Road, Race Course Road, Bangalore                 37
The Oberoi, 37-39, MG Road, Bangalore                                     36
Vivanta By Taj, 41/3, MG Road, Bangalore                                  35
2, 2nd Floor, 100 Feet Road, Koramangala 5th Block, Bangalore             35
18, Ali Askar Road, Cunningham Road, Bangalore                            34
15/A, 4th Main, Behind Ayyappa Swamy Temple, Madiwala, BTM, Bangalore     33
Name: count, dtype: int64

In [29]:
print("\nVotes Values:")
print(df["votes"].value_counts(dropna=False).head(15))

Votes Values:
votes
0     10027
4      1140
6       992
7       872
9       738
11      701
5       667
8       626
10      621
16      535
13      465
12      465
17      452
14      434
23      408
Name: count, dtype: int64

In [30]:
print("\nName Values:")
print(df["name"].value_counts(dropna=False).head(15))

Name Values:
name
Cafe Coffee Day      96
Onesta               85
Just Bake            73
Empire Restaurant    71
Five Star Chicken    70
Kanti Sweets         68
Petoo                66
Polar Bear           65
Baskin Robbins       64
Pizza Hut            62
Chef Baker's         62
Sweet Truth          60
Domino's Pizza       60
Beijing Bites        60
KFC                  60
Name: count, dtype: int64

In [18]:
print("\nOnline Order Values:")
print(df["online_order"].value_counts(dropna=False))

Online Order Values:
online_order
Yes    30444
No     21273
Name: count, dtype: int64

In [20]:
print("\nBook Table Values:")
print(df["book_table"].value_counts(dropna=False))

Book Table Values:
book_table
No     45268
Yes     6449
Name: count, dtype: int64

## Data Cleaning

# 1.rate

In [32]:
zomato = df.copy()

In [33]:
zomato["rate"] = (
    zomato["rate"]
    .str.strip()
    .str.replace(" ", "", regex=False)
    .str.replace("/5", "", regex=False)
)

In [34]:
zomato["rate"] = pd.to_numeric(
    zomato["rate"],
    errors="coerce")

In [35]:
print(zomato["rate"].value_counts(dropna=False).head(15))
print("\nData Type:", zomato["rate"].dtype)

rate
NaN    10052
3.9     3972
3.8     3873
3.7     3821
3.6     3316
4.0     3183
4.1     2948
3.5     2784
3.4     2476
3.3     2310
4.2     2184
3.2     1873
4.3     1693
3.1     1561
4.4     1147
Name: count, dtype: int64

Data Type: float64

# 2.cost col

In [36]:
cost_col = "approx_cost(for two people)"

In [37]:
zomato[cost_col] = (
    zomato[cost_col]
    .str.replace(",", "", regex=False)
    .str.strip()
)

In [38]:
zomato[cost_col] = pd.to_numeric(
    zomato[cost_col],
    errors="coerce"
)

In [40]:
print(zomato[cost_col].value_counts(dropna=False).head(15))
print("\nData Type:", zomato[cost_col].dtype)

approx_cost(for two people)
300.0     7576
400.0     6562
500.0     4980
200.0     4857
600.0     3714
250.0     2959
800.0     2285
150.0     2066
700.0     1948
350.0     1763
1000.0    1637
450.0     1417
100.0      993
1200.0     993
1500.0     971
Name: count, dtype: int64

Data Type: float64

## Validation

In [42]:
print("Rate Data Type:", zomato["rate"].dtype)
print("Cost Data Type:", zomato[cost_col].dtype)

Rate Data Type: float64
Cost Data Type: float64

In [44]:
print("\nMissing Values After Cleaning:")
print(zomato[["rate", cost_col]].isnull().sum())

Missing Values After Cleaning:
rate                           10052
approx_cost(for two people)      346
dtype: int64

In [46]:
print("\nRating Range:")
print(zomato["rate"].min(), "to", zomato["rate"].max())

Rating Range:
1.8 to 4.9

In [47]:
print("\nCost Statistics:")
print(zomato[cost_col].describe())

Cost Statistics:
count    51371.000000
mean       555.431566
std        438.850728
min         40.000000
25%        300.000000
50%        400.000000
75%        650.000000
max       6000.000000
Name: approx_cost(for two people), dtype: float64

In [48]:
text_columns = [
    "url",
    "address",
    "name",
    "online_order",
    "book_table",
    "phone",
    "location",
    "rest_type",
    "dish_liked",
    "cuisines",
    "reviews_list",
    "menu_item",
    "listed_in(type)",
    "listed_in(city)"
]

zomato[text_columns] = zomato[text_columns].apply(
    lambda col: col.str.strip()
)

In [54]:
print("\nMissing Values:")
missing_values_zomato = zomato.isnull().sum().sort_values(ascending=False)
missing_values_zomato

Missing Values:

dish_liked                     28078
rate                           10052
phone                           1208
approx_cost(for two people)      346
rest_type                        227
cuisines                          45
location                          21
url                                0
address                            0
votes                              0
name                               0
online_order                       0
book_table                         0
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [55]:
print("\nOnline Order Values:")
print(zomato["online_order"].value_counts(dropna=False))

Online Order Values:
online_order
Yes    30444
No     21273
Name: count, dtype: int64

In [56]:
print("\nBook Table Values:")
print(zomato["book_table"].value_counts(dropna=False))

Book Table Values:
book_table
No     45268
Yes     6449
Name: count, dtype: int64

In [58]:
print("Missing Rest Type:")
print(zomato[zomato["rest_type"].isnull()][
    ["name", "location", "rest_type"]
].head(10))

Missing Rest Type:
                      name           location rest_type
999        Mughlai Kitchen                BTM       NaN
1300  Eat & Joy Restaurant           JP Nagar       NaN
1376   Kababish Restaurant                BTM       NaN
1565    Goli Vada Pav No 1  Bannerghatta Road       NaN
1637        Ammi's Biryani  Bannerghatta Road       NaN
1662       Papa Khan Rasoi                NaN       NaN
1822          Bottle Genie           JP Nagar       NaN
2023    Goli Vada Pav No 1  Bannerghatta Road       NaN
2044        Ammi's Biryani  Bannerghatta Road       NaN
2330          Bottle Genie           JP Nagar       NaN

In [59]:
print("\nMissing Cuisines:")
print(zomato[zomato["cuisines"].isnull()][
    ["name", "location", "cuisines"]
].head(10))

Missing Cuisines:
                      name            location cuisines
438   The House Of Vadapav        Banashankari      NaN
440             Lassi Spot  Kumaraswamy Layout      NaN
759   The House Of Vadapav        Banashankari      NaN
1662       Papa Khan Rasoi                 NaN      NaN
4037            Chai Point        Marathahalli      NaN
6887          Noodle Oodle          Whitefield      NaN
6897    Taste of Chettinad          Whitefield      NaN
7277          Watheen Nuts          Whitefield      NaN
7555    Delhi Food Factory        Marathahalli      NaN
9874       Papa Khan Rasoi                 NaN      NaN

In [60]:
print("\nMissing Location:")
print(zomato[zomato["location"].isnull()][
    ["name", "address", "location"]
].head(10))

Missing Location:
                            name  \
1662             Papa Khan Rasoi
9874             Papa Khan Rasoi
13693   Mohabbat Desi Restaurant
16351              Desi Chatkara
26432     New Taj Biryani Centre
26519  AB's - Absolute Barbecues
27672                    Manchow
28611                    Manchow
29298  AB's - Absolute Barbecues
30604                    Manchow

                                                 address location
1662   6, Abbiah Layout KC Halli Main Road, Bommanaha...      NaN
9874   6, Abbiah Layout KC Halli Main Road, Bommanaha...      NaN
13693  Chandapura- Anakal Main Road, Oppsite Vemana H...      NaN
16351                Kudlu Gate, Bommanahalli, Bangalore      NaN
26432  IB Road, Lorry Stand, Kushaal Nagar, Ward 10, ...      NaN
26519                   Koramangala 8th Block, Bangalore      NaN
27672  6, Kathalipalya Village, 6th Cross, Koramangal...      NaN
28611  6, Kathalipalya Village, 6th Cross, Koramangal...      NaN
29298                   Koramangala 8th Block, Bangalore      NaN
30604  6, Kathalipalya Village, 6th Cross, Koramangal...      NaN

In [61]:
print("\nMissing Cost:")
print(zomato[zomato["approx_cost(for two people)"].isnull()][
    ["name", "location", "approx_cost(for two people)"]
].head(10))

Missing Cost:
                                name           location  \
1662                 Papa Khan Rasoi                NaN
1768                          Innate           JP Nagar
1795  Super Chef's (New Royal treat)  Bannerghatta Road
3069  Super Chef's (New Royal treat)  Bannerghatta Road
3774        The Hub - Ibis Bengaluru       Marathahalli
3954            North Indian Kitchen                HSR
4040                   Only Parathas                HSR
4421                          Innate      Sarjapur Road
4852        The Hub - Ibis Bengaluru       Marathahalli
4952        The Hub - Ibis Bengaluru       Marathahalli

      approx_cost(for two people)
1662                          NaN
1768                          NaN
1795                          NaN
3069                          NaN
3774                          NaN
3954                          NaN
4040                          NaN
4421                          NaN
4852                          NaN
4952                          NaN

In [62]:
print("Rating Values Outside Expected Range:")
print(zomato[
    (zomato["rate"] < 0) | (zomato["rate"] > 5)
]["rate"].head(10))

Rating Values Outside Expected Range:
Series([], Name: rate, dtype: float64)

In [63]:
print("\nNegative Votes:")
print(zomato[zomato["votes"] < 0]["votes"].head(10))

Negative Votes:
Series([], Name: votes, dtype: int64)

In [64]:
print("\nZero Votes:")
print((zomato["votes"] == 0).sum())

Zero Votes:
10027

In [65]:
print("\nZero or Negative Cost:")
print(zomato[
    zomato["approx_cost(for two people)"] <= 0
]["approx_cost(for two people)"].head(10))

Zero or Negative Cost:
Series([], Name: approx_cost(for two people), dtype: float64)

In [71]:
zomato[text_columns] = zomato[text_columns].fillna("Unknown")

In [72]:
print("Final Dataset Information:")
zomato.info()

Final Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         41665 non-null  float64
 6   votes                        51717 non-null  int64
 7   phone                        51717 non-null  str
 8   location                     51717 non-null  str
 9   rest_type                    51717 non-null  str
 10  dish_liked                   51717 non-null  str
 11  cuisines                     51717 non-null  str
 12  approx_cost(for two people)  51371 non-null  float64
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: float64(2), int64(1), str(14)
memory usage: 6.7 MB

In [73]:
print("\nMissing Values:")
print(zomato.isnull().sum())

Missing Values:
url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                           10052
votes                              0
phone                              0
location                           0
rest_type                          0
dish_liked                         0
cuisines                           0
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [74]:
print("\nFirst 5 Rows:")
display(zomato.head())

First 5 Rows:

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [75]:
zomato.to_csv("zomato_cleaned.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!